"""Initial schema

Revision ID: afb6e5aae612
Revises:
Create Date: 2025-11-09 19:46:28.971613

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "afb6e5aae612"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
